In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("final_dataset.csv")
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,LBH,LBD,LBA,SJH,SJD,SJA
0,E0,11/08/2023,20:00,Burnley,Man City,0.0,3.0,A,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2.0,1.0,H,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1.0,1.0,D,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,12/08/2023,15:00,Brighton,Luton,4.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,12/08/2023,15:00,Everton,Fulham,0.0,1.0,A,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4064,E0,11/05/2014,NaN,Norwich,Arsenal,0.0,2.0,A,0.0,0.0,...,1.85,1.80,2.12,2.07,3.80,3.6,1.90,4.33,3.50,1.83
4065,E0,11/05/2014,NaN,Southampton,Man United,1.0,1.0,D,1.0,0.0,...,1.90,1.86,2.06,1.99,2.62,3.4,2.62,2.60,3.30,2.75
4066,E0,11/05/2014,NaN,Sunderland,Swansea,1.0,3.0,A,0.0,2.0,...,2.40,2.30,1.68,1.63,2.10,3.4,3.40,2.30,3.25,3.13
4067,E0,11/05/2014,NaN,Tottenham,Aston Villa,3.0,0.0,H,3.0,0.0,...,1.86,1.77,2.20,2.10,1.50,4.2,6.50,1.50,4.00,6.50
4068,E0,11/05/2014,NaN,West Brom,Stoke,1.0,2.0,A,0.0,1.0,...,1.85,1.76,2.18,2.11,2.10,3.5,3.30,2.00,3.40,3.75

In [ ]:
def get_season(date):
    year = date.year
    month = date.month
    # Define the usual season start and end months
    season_start_month = 8
    season_end_month = 6
    
    # Special handling for the pandemic season
    pandemic_season_year = 2020
    pandemic_season_end_month = 7  # July
    
    # For months January to June, the season started in the previous year
    if month <= season_end_month:
        season_start_year = year - 1
    # For the pandemic-affected year, extend the season to include July
    elif year == pandemic_season_year and month == pandemic_season_end_month:
        season_start_year = year - 1
    # For months August to December, the season starts in the current year
    else:
        season_start_year = year

    season_end_year = season_start_year + 1
    # Format season as "YY/YY"
    return f'{str(season_start_year)[-2:]}/{str(season_end_year)[-2:]}'